// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByjsZ3XvzAPNK1jpOkGpbbRrQEYGvSMy0',
    appId: '1:1014191653044:web:bc18a065ca983d202e57e1',
    messagingSenderId: '1014191653044',
    projectId: 'lista-de-contatos-e74a3',
    authDomain: 'lista-de-contatos-e74a3.firebaseapp.com',
    databaseURL: 'https://lista-de-contatos-e74a3-default-rtdb.firebaseio.com',
    storageBucket: 'lista-de-contatos-e74a3.appspot.com',
    measurementId: 'G-DQ9HRGLV40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtrmKKwo6eei9lhuYM9ttWrB7UvNXwZdc',
    appId: '1:1014191653044:android:20e49e0f2746f6532e57e1',
    messagingSenderId: '1014191653044',
    projectId: 'lista-de-contatos-e74a3',
    databaseURL: 'https://lista-de-contatos-e74a3-default-rtdb.firebaseio.com',
    storageBucket: 'lista-de-contatos-e74a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgsn0qZ575baswXKqFCFmyoTnxohMrc7w',
    appId: '1:1014191653044:ios:f1554e8f44aad45a2e57e1',
    messagingSenderId: '1014191653044',
    projectId: 'lista-de-contatos-e74a3',
    databaseURL: 'https://lista-de-contatos-e74a3-default-rtdb.firebaseio.com',
    storageBucket: 'lista-de-contatos-e74a3.appspot.com',
    iosClientId: '1014191653044-d0cefpfgjr6th658cqh9g4j7o0h3ejq8.apps.googleusercontent.com',
    iosBundleId: 'app.projetoteste.meus_contatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgsn0qZ575baswXKqFCFmyoTnxohMrc7w',
    appId: '1:1014191653044:ios:f1554e8f44aad45a2e57e1',
    messagingSenderId: '1014191653044',
    projectId: 'lista-de-contatos-e74a3',
    databaseURL: 'https://lista-de-contatos-e74a3-default-rtdb.firebaseio.com',
    storageBucket: 'lista-de-contatos-e74a3.appspot.com',
    iosClientId: '1014191653044-d0cefpfgjr6th658cqh9g4j7o0h3ejq8.apps.googleusercontent.com',
    iosBundleId: 'app.projetoteste.meus_contatos',
  );
}
